// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/internal/runtime (interfaces: EventBusRuntime)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	eventbus "github.com/agenticenv/agent-sdk-go/internal/eventbus"
	runtime "github.com/agenticenv/agent-sdk-go/internal/runtime"
	types "github.com/agenticenv/agent-sdk-go/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockEventBusRuntime is a mock of EventBusRuntime interface.
type MockEventBusRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockEventBusRuntimeMockRecorder
}

// MockEventBusRuntimeMockRecorder is the mock recorder for MockEventBusRuntime.
type MockEventBusRuntimeMockRecorder struct {
	mock *MockEventBusRuntime
}

// NewMockEventBusRuntime creates a new mock instance.
func NewMockEventBusRuntime(ctrl *gomock.Controller) *MockEventBusRuntime {
	mock := &MockEventBusRuntime{ctrl: ctrl}
	mock.recorder = &MockEventBusRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBusRuntime) EXPECT() *MockEventBusRuntimeMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockEventBusRuntime) Approve(arg0 context.Context, arg1 string, arg2 types.ApprovalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockEventBusRuntimeMockRecorder) Approve(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockEventBusRuntime)(nil).Approve), arg0, arg1, arg2)
}

// Close mocks base method.
func (m *MockEventBusRuntime) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockEventBusRuntimeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventBusRuntime)(nil).Close))
}

// Execute mocks base method.
func (m *MockEventBusRuntime) Execute(arg0 context.Context, arg1 *runtime.ExecuteRequest) (*types.AgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*types.AgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockEventBusRuntimeMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockEventBusRuntime)(nil).Execute), arg0, arg1)
}

// ExecuteStream mocks base method.
func (m *MockEventBusRuntime) ExecuteStream(arg0 context.Context, arg1 *runtime.ExecuteRequest) (chan *types.AgentEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStream", arg0, arg1)
	ret0, _ := ret[0].(chan *types.AgentEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteStream indicates an expected call of ExecuteStream.
func (mr *MockEventBusRuntimeMockRecorder) ExecuteStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStream", reflect.TypeOf((*MockEventBusRuntime)(nil).ExecuteStream), arg0, arg1)
}

// GetEventBus mocks base method.
func (m *MockEventBusRuntime) GetEventBus() eventbus.EventBus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventBus")
	ret0, _ := ret[0].(eventbus.EventBus)
	return ret0
}

// GetEventBus indicates an expected call of GetEventBus.
func (mr *MockEventBusRuntimeMockRecorder) GetEventBus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventBus", reflect.TypeOf((*MockEventBusRuntime)(nil).GetEventBus))
}

// SetEventBus mocks base method.
func (m *MockEventBusRuntime) SetEventBus(arg0 eventbus.EventBus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEventBus", arg0)
}

// SetEventBus indicates an expected call of SetEventBus.
func (mr *MockEventBusRuntimeMockRecorder) SetEventBus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEventBus", reflect.TypeOf((*MockEventBusRuntime)(nil).SetEventBus), arg0)
}
