// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/internal/runtime (interfaces: Runtime)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	eventbus "github.com/agenticenv/agent-sdk-go/internal/eventbus"
	runtime "github.com/agenticenv/agent-sdk-go/internal/runtime"
	types "github.com/agenticenv/agent-sdk-go/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockRuntime) Approve(arg0 context.Context, arg1 string, arg2 types.ApprovalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockRuntimeMockRecorder) Approve(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockRuntime)(nil).Approve), arg0, arg1, arg2)
}

// Close mocks base method.
func (m *MockRuntime) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRuntimeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRuntime)(nil).Close))
}

// GetEventBus mocks base method.
func (m *MockRuntime) GetEventBus() eventbus.EventBus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventBus")
	ret0, _ := ret[0].(eventbus.EventBus)
	return ret0
}

// GetEventBus indicates an expected call of GetEventBus.
func (mr *MockRuntimeMockRecorder) GetEventBus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventBus", reflect.TypeOf((*MockRuntime)(nil).GetEventBus))
}

// Run mocks base method.
func (m *MockRuntime) Run(arg0 context.Context, arg1 *runtime.RunRequest) (*types.AgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(*types.AgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockRuntimeMockRecorder) Run(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRuntime)(nil).Run), arg0, arg1)
}

// RunStream mocks base method.
func (m *MockRuntime) RunStream(arg0 context.Context, arg1 *runtime.RunRequest) (chan *types.AgentEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunStream", arg0, arg1)
	ret0, _ := ret[0].(chan *types.AgentEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunStream indicates an expected call of RunStream.
func (mr *MockRuntimeMockRecorder) RunStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunStream", reflect.TypeOf((*MockRuntime)(nil).RunStream), arg0, arg1)
}

// SetEventBus mocks base method.
func (m *MockRuntime) SetEventBus(arg0 eventbus.EventBus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEventBus", arg0)
}

// SetEventBus indicates an expected call of SetEventBus.
func (mr *MockRuntimeMockRecorder) SetEventBus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEventBus", reflect.TypeOf((*MockRuntime)(nil).SetEventBus), arg0)
}

// Start mocks base method.
func (m *MockRuntime) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRuntimeMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRuntime)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockRuntime) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockRuntimeMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRuntime)(nil).Stop))
}
