// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/internal/runtime (interfaces: WorkerRuntime)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	runtime "github.com/agenticenv/agent-sdk-go/internal/runtime"
	types "github.com/agenticenv/agent-sdk-go/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockWorkerRuntime is a mock of WorkerRuntime interface.
type MockWorkerRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRuntimeMockRecorder
}

// MockWorkerRuntimeMockRecorder is the mock recorder for MockWorkerRuntime.
type MockWorkerRuntimeMockRecorder struct {
	mock *MockWorkerRuntime
}

// NewMockWorkerRuntime creates a new mock instance.
func NewMockWorkerRuntime(ctrl *gomock.Controller) *MockWorkerRuntime {
	mock := &MockWorkerRuntime{ctrl: ctrl}
	mock.recorder = &MockWorkerRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRuntime) EXPECT() *MockWorkerRuntimeMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockWorkerRuntime) Approve(arg0 context.Context, arg1 string, arg2 types.ApprovalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockWorkerRuntimeMockRecorder) Approve(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockWorkerRuntime)(nil).Approve), arg0, arg1, arg2)
}

// Close mocks base method.
func (m *MockWorkerRuntime) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWorkerRuntimeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkerRuntime)(nil).Close))
}

// Execute mocks base method.
func (m *MockWorkerRuntime) Execute(arg0 context.Context, arg1 *runtime.ExecuteRequest) (*types.AgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*types.AgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockWorkerRuntimeMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockWorkerRuntime)(nil).Execute), arg0, arg1)
}

// ExecuteStream mocks base method.
func (m *MockWorkerRuntime) ExecuteStream(arg0 context.Context, arg1 *runtime.ExecuteRequest) (chan *types.AgentEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStream", arg0, arg1)
	ret0, _ := ret[0].(chan *types.AgentEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteStream indicates an expected call of ExecuteStream.
func (mr *MockWorkerRuntimeMockRecorder) ExecuteStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStream", reflect.TypeOf((*MockWorkerRuntime)(nil).ExecuteStream), arg0, arg1)
}

// Start mocks base method.
func (m *MockWorkerRuntime) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWorkerRuntimeMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWorkerRuntime)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockWorkerRuntime) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockWorkerRuntimeMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWorkerRuntime)(nil).Stop))
}
