// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/agent (interfaces: ToolRegistry,MCPRegistry,A2ARegistry,SubAgentRegistry)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	agent "github.com/agenticenv/agent-sdk-go/pkg/agent"
	interfaces "github.com/agenticenv/agent-sdk-go/pkg/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockToolRegistry is a mock of ToolRegistry interface.
type MockToolRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockToolRegistryMockRecorder
}

// MockToolRegistryMockRecorder is the mock recorder for MockToolRegistry.
type MockToolRegistryMockRecorder struct {
	mock *MockToolRegistry
}

// NewMockToolRegistry creates a new mock instance.
func NewMockToolRegistry(ctrl *gomock.Controller) *MockToolRegistry {
	mock := &MockToolRegistry{ctrl: ctrl}
	mock.recorder = &MockToolRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolRegistry) EXPECT() *MockToolRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockToolRegistry) Get(arg0 string) (interfaces.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(interfaces.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockToolRegistryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockToolRegistry)(nil).Get), arg0)
}

// List mocks base method.
func (m *MockToolRegistry) List() []interfaces.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]interfaces.Tool)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockToolRegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockToolRegistry)(nil).List))
}

// Register mocks base method.
func (m *MockToolRegistry) Register(arg0 interfaces.Tool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockToolRegistryMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockToolRegistry)(nil).Register), arg0)
}

// Unregister mocks base method.
func (m *MockToolRegistry) Unregister(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockToolRegistryMockRecorder) Unregister(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockToolRegistry)(nil).Unregister), arg0)
}

// MockMCPRegistry is a mock of MCPRegistry interface.
type MockMCPRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockMCPRegistryMockRecorder
}

// MockMCPRegistryMockRecorder is the mock recorder for MockMCPRegistry.
type MockMCPRegistryMockRecorder struct {
	mock *MockMCPRegistry
}

// NewMockMCPRegistry creates a new mock instance.
func NewMockMCPRegistry(ctrl *gomock.Controller) *MockMCPRegistry {
	mock := &MockMCPRegistry{ctrl: ctrl}
	mock.recorder = &MockMCPRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPRegistry) EXPECT() *MockMCPRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMCPRegistry) Get(arg0 string) (interfaces.MCPClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(interfaces.MCPClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMCPRegistryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMCPRegistry)(nil).Get), arg0)
}

// List mocks base method.
func (m *MockMCPRegistry) List() []interfaces.MCPClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]interfaces.MCPClient)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockMCPRegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMCPRegistry)(nil).List))
}

// Register mocks base method.
func (m *MockMCPRegistry) Register(arg0 string, arg1 agent.MCPConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockMCPRegistryMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockMCPRegistry)(nil).Register), arg0, arg1)
}

// RegisterClient mocks base method.
func (m *MockMCPRegistry) RegisterClient(arg0 interfaces.MCPClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterClient", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockMCPRegistryMockRecorder) RegisterClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockMCPRegistry)(nil).RegisterClient), arg0)
}

// Unregister mocks base method.
func (m *MockMCPRegistry) Unregister(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockMCPRegistryMockRecorder) Unregister(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockMCPRegistry)(nil).Unregister), arg0)
}

// MockA2ARegistry is a mock of A2ARegistry interface.
type MockA2ARegistry struct {
	ctrl     *gomock.Controller
	recorder *MockA2ARegistryMockRecorder
}

// MockA2ARegistryMockRecorder is the mock recorder for MockA2ARegistry.
type MockA2ARegistryMockRecorder struct {
	mock *MockA2ARegistry
}

// NewMockA2ARegistry creates a new mock instance.
func NewMockA2ARegistry(ctrl *gomock.Controller) *MockA2ARegistry {
	mock := &MockA2ARegistry{ctrl: ctrl}
	mock.recorder = &MockA2ARegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockA2ARegistry) EXPECT() *MockA2ARegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockA2ARegistry) Get(arg0 string) (interfaces.A2AClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(interfaces.A2AClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockA2ARegistryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockA2ARegistry)(nil).Get), arg0)
}

// List mocks base method.
func (m *MockA2ARegistry) List() []interfaces.A2AClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]interfaces.A2AClient)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockA2ARegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockA2ARegistry)(nil).List))
}

// Register mocks base method.
func (m *MockA2ARegistry) Register(arg0 string, arg1 agent.A2AConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockA2ARegistryMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockA2ARegistry)(nil).Register), arg0, arg1)
}

// RegisterClient mocks base method.
func (m *MockA2ARegistry) RegisterClient(arg0 interfaces.A2AClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterClient", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockA2ARegistryMockRecorder) RegisterClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockA2ARegistry)(nil).RegisterClient), arg0)
}

// Unregister mocks base method.
func (m *MockA2ARegistry) Unregister(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockA2ARegistryMockRecorder) Unregister(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockA2ARegistry)(nil).Unregister), arg0)
}

// MockSubAgentRegistry is a mock of SubAgentRegistry interface.
type MockSubAgentRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSubAgentRegistryMockRecorder
}

// MockSubAgentRegistryMockRecorder is the mock recorder for MockSubAgentRegistry.
type MockSubAgentRegistryMockRecorder struct {
	mock *MockSubAgentRegistry
}

// NewMockSubAgentRegistry creates a new mock instance.
func NewMockSubAgentRegistry(ctrl *gomock.Controller) *MockSubAgentRegistry {
	mock := &MockSubAgentRegistry{ctrl: ctrl}
	mock.recorder = &MockSubAgentRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubAgentRegistry) EXPECT() *MockSubAgentRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSubAgentRegistry) Get(arg0 string) (*agent.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*agent.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubAgentRegistryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubAgentRegistry)(nil).Get), arg0)
}

// List mocks base method.
func (m *MockSubAgentRegistry) List() []*agent.Agent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*agent.Agent)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockSubAgentRegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubAgentRegistry)(nil).List))
}

// Register mocks base method.
func (m *MockSubAgentRegistry) Register(arg0 *agent.Agent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockSubAgentRegistryMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockSubAgentRegistry)(nil).Register), arg0)
}

// Unregister mocks base method.
func (m *MockSubAgentRegistry) Unregister(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockSubAgentRegistryMockRecorder) Unregister(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockSubAgentRegistry)(nil).Unregister), arg0)
}
