// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vvsynapse/temporal-agent-sdk-go/pkg/interfaces (interfaces: Conversation)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/vvsynapse/temporal-agent-sdk-go/pkg/interfaces"
)

// MockConversation is a mock of Conversation interface.
type MockConversation struct {
	ctrl     *gomock.Controller
	recorder *MockConversationMockRecorder
}

// MockConversationMockRecorder is the mock recorder for MockConversation.
type MockConversationMockRecorder struct {
	mock *MockConversation
}

// NewMockConversation creates a new mock instance.
func NewMockConversation(ctrl *gomock.Controller) *MockConversation {
	mock := &MockConversation{ctrl: ctrl}
	mock.recorder = &MockConversationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversation) EXPECT() *MockConversationMockRecorder {
	return m.recorder
}

// AddMessage mocks base method.
func (m *MockConversation) AddMessage(arg0 context.Context, arg1 string, arg2 interfaces.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessage indicates an expected call of AddMessage.
func (mr *MockConversationMockRecorder) AddMessage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessage", reflect.TypeOf((*MockConversation)(nil).AddMessage), arg0, arg1, arg2)
}

// Clear mocks base method.
func (m *MockConversation) Clear(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockConversationMockRecorder) Clear(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockConversation)(nil).Clear), arg0, arg1)
}

// IsDistributed mocks base method.
func (m *MockConversation) IsDistributed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDistributed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDistributed indicates an expected call of IsDistributed.
func (mr *MockConversationMockRecorder) IsDistributed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDistributed", reflect.TypeOf((*MockConversation)(nil).IsDistributed))
}

// ListMessages mocks base method.
func (m *MockConversation) ListMessages(arg0 context.Context, arg1 string, arg2 ...interfaces.ListMessagesOption) ([]interfaces.Message, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMessages", varargs...)
	ret0, _ := ret[0].([]interfaces.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockConversationMockRecorder) ListMessages(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockConversation)(nil).ListMessages), varargs...)
}
