// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/interfaces (interfaces: Memory)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/agenticenv/agent-sdk-go/pkg/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockMemory is a mock of Memory interface.
type MockMemory struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryMockRecorder
}

// MockMemoryMockRecorder is the mock recorder for MockMemory.
type MockMemoryMockRecorder struct {
	mock *MockMemory
}

// NewMockMemory creates a new mock instance.
func NewMockMemory(ctrl *gomock.Controller) *MockMemory {
	mock := &MockMemory{ctrl: ctrl}
	mock.recorder = &MockMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemory) EXPECT() *MockMemoryMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockMemory) Clear(arg0 context.Context, arg1 interfaces.MemoryScope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockMemoryMockRecorder) Clear(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockMemory)(nil).Clear), arg0, arg1)
}

// Load mocks base method.
func (m *MockMemory) Load(arg0 context.Context, arg1 interfaces.MemoryScope, arg2 string, arg3 ...interfaces.LoadMemoryOption) ([]interfaces.MemoryEntry, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Load", varargs...)
	ret0, _ := ret[0].([]interfaces.MemoryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockMemoryMockRecorder) Load(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockMemory)(nil).Load), varargs...)
}

// Store mocks base method.
func (m *MockMemory) Store(arg0 context.Context, arg1 interfaces.MemoryScope, arg2 interfaces.MemoryRecord, arg3 ...interfaces.StoreMemoryOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Store", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockMemoryMockRecorder) Store(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMemory)(nil).Store), varargs...)
}
