// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/interfaces (interfaces: Tool,ToolRegistry)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/agenticenv/agent-sdk-go/pkg/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockTool is a mock of Tool interface.
type MockTool struct {
	ctrl     *gomock.Controller
	recorder *MockToolMockRecorder
}

// MockToolMockRecorder is the mock recorder for MockTool.
type MockToolMockRecorder struct {
	mock *MockTool
}

// NewMockTool creates a new mock instance.
func NewMockTool(ctrl *gomock.Controller) *MockTool {
	mock := &MockTool{ctrl: ctrl}
	mock.recorder = &MockToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTool) EXPECT() *MockToolMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockTool) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockToolMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockTool)(nil).Description))
}

// Execute mocks base method.
func (m *MockTool) Execute(arg0 context.Context, arg1 map[string]interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTool)(nil).Execute), arg0, arg1)
}

// Name mocks base method.
func (m *MockTool) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockToolMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTool)(nil).Name))
}

// Parameters mocks base method.
func (m *MockTool) Parameters() interfaces.JSONSchema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parameters")
	ret0, _ := ret[0].(interfaces.JSONSchema)
	return ret0
}

// Parameters indicates an expected call of Parameters.
func (mr *MockToolMockRecorder) Parameters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parameters", reflect.TypeOf((*MockTool)(nil).Parameters))
}

// MockToolRegistry is a mock of ToolRegistry interface.
type MockToolRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockToolRegistryMockRecorder
}

// MockToolRegistryMockRecorder is the mock recorder for MockToolRegistry.
type MockToolRegistryMockRecorder struct {
	mock *MockToolRegistry
}

// NewMockToolRegistry creates a new mock instance.
func NewMockToolRegistry(ctrl *gomock.Controller) *MockToolRegistry {
	mock := &MockToolRegistry{ctrl: ctrl}
	mock.recorder = &MockToolRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolRegistry) EXPECT() *MockToolRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockToolRegistry) Get(arg0 string) (interfaces.Tool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(interfaces.Tool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockToolRegistryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockToolRegistry)(nil).Get), arg0)
}

// Register mocks base method.
func (m *MockToolRegistry) Register(arg0 interfaces.Tool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", arg0)
}

// Register indicates an expected call of Register.
func (mr *MockToolRegistryMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockToolRegistry)(nil).Register), arg0)
}

// Tools mocks base method.
func (m *MockToolRegistry) Tools() []interfaces.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tools")
	ret0, _ := ret[0].([]interfaces.Tool)
	return ret0
}

// Tools indicates an expected call of Tools.
func (mr *MockToolRegistryMockRecorder) Tools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tools", reflect.TypeOf((*MockToolRegistry)(nil).Tools))
}
