// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vvsynapse/temporal-agent-sdk-go/pkg/interfaces (interfaces: LLMClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/vvsynapse/temporal-agent-sdk-go/pkg/interfaces"
)

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockLLMClient) Generate(arg0 context.Context, arg1 *interfaces.LLMRequest) (*interfaces.LLMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", arg0, arg1)
	ret0, _ := ret[0].(*interfaces.LLMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockLLMClientMockRecorder) Generate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockLLMClient)(nil).Generate), arg0, arg1)
}

// GenerateStream mocks base method.
func (m *MockLLMClient) GenerateStream(arg0 context.Context, arg1 *interfaces.LLMRequest) (interfaces.LLMStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStream", arg0, arg1)
	ret0, _ := ret[0].(interfaces.LLMStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStream indicates an expected call of GenerateStream.
func (mr *MockLLMClientMockRecorder) GenerateStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStream", reflect.TypeOf((*MockLLMClient)(nil).GenerateStream), arg0, arg1)
}

// GetModel mocks base method.
func (m *MockLLMClient) GetModel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetModel indicates an expected call of GetModel.
func (mr *MockLLMClientMockRecorder) GetModel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockLLMClient)(nil).GetModel))
}

// GetProvider mocks base method.
func (m *MockLLMClient) GetProvider() interfaces.LLMProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider")
	ret0, _ := ret[0].(interfaces.LLMProvider)
	return ret0
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockLLMClientMockRecorder) GetProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockLLMClient)(nil).GetProvider))
}

// IsStreamSupported mocks base method.
func (m *MockLLMClient) IsStreamSupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStreamSupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStreamSupported indicates an expected call of IsStreamSupported.
func (mr *MockLLMClientMockRecorder) IsStreamSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStreamSupported", reflect.TypeOf((*MockLLMClient)(nil).IsStreamSupported))
}
