// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/interfaces (interfaces: AgentToolApprovalPolicy)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	interfaces "github.com/agenticenv/agent-sdk-go/pkg/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockAgentToolApprovalPolicy is a mock of AgentToolApprovalPolicy interface.
type MockAgentToolApprovalPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockAgentToolApprovalPolicyMockRecorder
}

// MockAgentToolApprovalPolicyMockRecorder is the mock recorder for MockAgentToolApprovalPolicy.
type MockAgentToolApprovalPolicyMockRecorder struct {
	mock *MockAgentToolApprovalPolicy
}

// NewMockAgentToolApprovalPolicy creates a new mock instance.
func NewMockAgentToolApprovalPolicy(ctrl *gomock.Controller) *MockAgentToolApprovalPolicy {
	mock := &MockAgentToolApprovalPolicy{ctrl: ctrl}
	mock.recorder = &MockAgentToolApprovalPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentToolApprovalPolicy) EXPECT() *MockAgentToolApprovalPolicyMockRecorder {
	return m.recorder
}

// RequiresApproval mocks base method.
func (m *MockAgentToolApprovalPolicy) RequiresApproval(arg0 interfaces.Tool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiresApproval", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RequiresApproval indicates an expected call of RequiresApproval.
func (mr *MockAgentToolApprovalPolicyMockRecorder) RequiresApproval(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiresApproval", reflect.TypeOf((*MockAgentToolApprovalPolicy)(nil).RequiresApproval), arg0)
}
