// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/interfaces (interfaces: Tool,ToolApproval,ToolAuthorizer,ToolKindProvider)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/agenticenv/agent-sdk-go/internal/types"
	interfaces "github.com/agenticenv/agent-sdk-go/pkg/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockTool is a mock of Tool interface.
type MockTool struct {
	ctrl     *gomock.Controller
	recorder *MockToolMockRecorder
}

// MockToolMockRecorder is the mock recorder for MockTool.
type MockToolMockRecorder struct {
	mock *MockTool
}

// NewMockTool creates a new mock instance.
func NewMockTool(ctrl *gomock.Controller) *MockTool {
	mock := &MockTool{ctrl: ctrl}
	mock.recorder = &MockToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTool) EXPECT() *MockToolMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockTool) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockToolMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockTool)(nil).Description))
}

// DisplayName mocks base method.
func (m *MockTool) DisplayName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayName")
	ret0, _ := ret[0].(string)
	return ret0
}

// DisplayName indicates an expected call of DisplayName.
func (mr *MockToolMockRecorder) DisplayName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayName", reflect.TypeOf((*MockTool)(nil).DisplayName))
}

// Execute mocks base method.
func (m *MockTool) Execute(arg0 context.Context, arg1 map[string]interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTool)(nil).Execute), arg0, arg1)
}

// Name mocks base method.
func (m *MockTool) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockToolMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTool)(nil).Name))
}

// Parameters mocks base method.
func (m *MockTool) Parameters() types.JSONSchema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parameters")
	ret0, _ := ret[0].(types.JSONSchema)
	return ret0
}

// Parameters indicates an expected call of Parameters.
func (mr *MockToolMockRecorder) Parameters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parameters", reflect.TypeOf((*MockTool)(nil).Parameters))
}

// MockToolApproval is a mock of ToolApproval interface.
type MockToolApproval struct {
	ctrl     *gomock.Controller
	recorder *MockToolApprovalMockRecorder
}

// MockToolApprovalMockRecorder is the mock recorder for MockToolApproval.
type MockToolApprovalMockRecorder struct {
	mock *MockToolApproval
}

// NewMockToolApproval creates a new mock instance.
func NewMockToolApproval(ctrl *gomock.Controller) *MockToolApproval {
	mock := &MockToolApproval{ctrl: ctrl}
	mock.recorder = &MockToolApprovalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolApproval) EXPECT() *MockToolApprovalMockRecorder {
	return m.recorder
}

// ApprovalRequired mocks base method.
func (m *MockToolApproval) ApprovalRequired() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovalRequired")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ApprovalRequired indicates an expected call of ApprovalRequired.
func (mr *MockToolApprovalMockRecorder) ApprovalRequired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovalRequired", reflect.TypeOf((*MockToolApproval)(nil).ApprovalRequired))
}

// MockToolAuthorizer is a mock of ToolAuthorizer interface.
type MockToolAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockToolAuthorizerMockRecorder
}

// MockToolAuthorizerMockRecorder is the mock recorder for MockToolAuthorizer.
type MockToolAuthorizerMockRecorder struct {
	mock *MockToolAuthorizer
}

// NewMockToolAuthorizer creates a new mock instance.
func NewMockToolAuthorizer(ctrl *gomock.Controller) *MockToolAuthorizer {
	mock := &MockToolAuthorizer{ctrl: ctrl}
	mock.recorder = &MockToolAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolAuthorizer) EXPECT() *MockToolAuthorizerMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockToolAuthorizer) Authorize(arg0 context.Context, arg1 map[string]interface{}) (interfaces.ToolAuthorizationDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", arg0, arg1)
	ret0, _ := ret[0].(interfaces.ToolAuthorizationDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockToolAuthorizerMockRecorder) Authorize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockToolAuthorizer)(nil).Authorize), arg0, arg1)
}

// MockToolKindProvider is a mock of ToolKindProvider interface.
type MockToolKindProvider struct {
	ctrl     *gomock.Controller
	recorder *MockToolKindProviderMockRecorder
}

// MockToolKindProviderMockRecorder is the mock recorder for MockToolKindProvider.
type MockToolKindProviderMockRecorder struct {
	mock *MockToolKindProvider
}

// NewMockToolKindProvider creates a new mock instance.
func NewMockToolKindProvider(ctrl *gomock.Controller) *MockToolKindProvider {
	mock := &MockToolKindProvider{ctrl: ctrl}
	mock.recorder = &MockToolKindProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolKindProvider) EXPECT() *MockToolKindProviderMockRecorder {
	return m.recorder
}

// ToolKind mocks base method.
func (m *MockToolKindProvider) ToolKind() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToolKind")
	ret0, _ := ret[0].(string)
	return ret0
}

// ToolKind indicates an expected call of ToolKind.
func (mr *MockToolKindProviderMockRecorder) ToolKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolKind", reflect.TypeOf((*MockToolKindProvider)(nil).ToolKind))
}
