// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/interfaces (interfaces: MCPClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	types "github.com/agenticenv/agent-sdk-go/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockMCPClient is a mock of MCPClient interface.
type MockMCPClient struct {
	ctrl     *gomock.Controller
	recorder *MockMCPClientMockRecorder
}

// MockMCPClientMockRecorder is the mock recorder for MockMCPClient.
type MockMCPClientMockRecorder struct {
	mock *MockMCPClient
}

// NewMockMCPClient creates a new mock instance.
func NewMockMCPClient(ctrl *gomock.Controller) *MockMCPClient {
	mock := &MockMCPClient{ctrl: ctrl}
	mock.recorder = &MockMCPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPClient) EXPECT() *MockMCPClientMockRecorder {
	return m.recorder
}

// CallTool mocks base method.
func (m *MockMCPClient) CallTool(arg0 context.Context, arg1 string, arg2 json.RawMessage) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallTool", arg0, arg1, arg2)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallTool indicates an expected call of CallTool.
func (mr *MockMCPClientMockRecorder) CallTool(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallTool", reflect.TypeOf((*MockMCPClient)(nil).CallTool), arg0, arg1, arg2)
}

// Close mocks base method.
func (m *MockMCPClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMCPClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMCPClient)(nil).Close))
}

// ListTools mocks base method.
func (m *MockMCPClient) ListTools(arg0 context.Context) ([]types.ToolSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTools", arg0)
	ret0, _ := ret[0].([]types.ToolSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTools indicates an expected call of ListTools.
func (mr *MockMCPClientMockRecorder) ListTools(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTools", reflect.TypeOf((*MockMCPClient)(nil).ListTools), arg0)
}

// Name mocks base method.
func (m *MockMCPClient) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMCPClientMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMCPClient)(nil).Name))
}

// Ping mocks base method.
func (m *MockMCPClient) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMCPClientMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMCPClient)(nil).Ping), arg0)
}
