// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/interfaces (interfaces: A2AClient,A2AStreamingClient,A2ATaskClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/agenticenv/agent-sdk-go/internal/types"
	interfaces "github.com/agenticenv/agent-sdk-go/pkg/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockA2AClient is a mock of A2AClient interface.
type MockA2AClient struct {
	ctrl     *gomock.Controller
	recorder *MockA2AClientMockRecorder
}

// MockA2AClientMockRecorder is the mock recorder for MockA2AClient.
type MockA2AClientMockRecorder struct {
	mock *MockA2AClient
}

// NewMockA2AClient creates a new mock instance.
func NewMockA2AClient(ctrl *gomock.Controller) *MockA2AClient {
	mock := &MockA2AClient{ctrl: ctrl}
	mock.recorder = &MockA2AClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockA2AClient) EXPECT() *MockA2AClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockA2AClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockA2AClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockA2AClient)(nil).Close))
}

// ListSkills mocks base method.
func (m *MockA2AClient) ListSkills(arg0 context.Context) ([]types.A2ASkillSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", arg0)
	ret0, _ := ret[0].([]types.A2ASkillSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockA2AClientMockRecorder) ListSkills(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockA2AClient)(nil).ListSkills), arg0)
}

// Name mocks base method.
func (m *MockA2AClient) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockA2AClientMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockA2AClient)(nil).Name))
}

// Ping mocks base method.
func (m *MockA2AClient) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockA2AClientMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockA2AClient)(nil).Ping), arg0)
}

// ResolveCard mocks base method.
func (m *MockA2AClient) ResolveCard(arg0 context.Context) (interfaces.A2AAgentCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCard", arg0)
	ret0, _ := ret[0].(interfaces.A2AAgentCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCard indicates an expected call of ResolveCard.
func (mr *MockA2AClientMockRecorder) ResolveCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCard", reflect.TypeOf((*MockA2AClient)(nil).ResolveCard), arg0)
}

// SendMessage mocks base method.
func (m *MockA2AClient) SendMessage(arg0 context.Context, arg1 interfaces.A2ASendMessageRequest) (interfaces.A2ASendMessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0, arg1)
	ret0, _ := ret[0].(interfaces.A2ASendMessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockA2AClientMockRecorder) SendMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockA2AClient)(nil).SendMessage), arg0, arg1)
}

// MockA2AStreamingClient is a mock of A2AStreamingClient interface.
type MockA2AStreamingClient struct {
	ctrl     *gomock.Controller
	recorder *MockA2AStreamingClientMockRecorder
}

// MockA2AStreamingClientMockRecorder is the mock recorder for MockA2AStreamingClient.
type MockA2AStreamingClientMockRecorder struct {
	mock *MockA2AStreamingClient
}

// NewMockA2AStreamingClient creates a new mock instance.
func NewMockA2AStreamingClient(ctrl *gomock.Controller) *MockA2AStreamingClient {
	mock := &MockA2AStreamingClient{ctrl: ctrl}
	mock.recorder = &MockA2AStreamingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockA2AStreamingClient) EXPECT() *MockA2AStreamingClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockA2AStreamingClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockA2AStreamingClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockA2AStreamingClient)(nil).Close))
}

// ListSkills mocks base method.
func (m *MockA2AStreamingClient) ListSkills(arg0 context.Context) ([]types.A2ASkillSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", arg0)
	ret0, _ := ret[0].([]types.A2ASkillSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockA2AStreamingClientMockRecorder) ListSkills(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockA2AStreamingClient)(nil).ListSkills), arg0)
}

// Name mocks base method.
func (m *MockA2AStreamingClient) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockA2AStreamingClientMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockA2AStreamingClient)(nil).Name))
}

// Ping mocks base method.
func (m *MockA2AStreamingClient) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockA2AStreamingClientMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockA2AStreamingClient)(nil).Ping), arg0)
}

// ResolveCard mocks base method.
func (m *MockA2AStreamingClient) ResolveCard(arg0 context.Context) (interfaces.A2AAgentCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCard", arg0)
	ret0, _ := ret[0].(interfaces.A2AAgentCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCard indicates an expected call of ResolveCard.
func (mr *MockA2AStreamingClientMockRecorder) ResolveCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCard", reflect.TypeOf((*MockA2AStreamingClient)(nil).ResolveCard), arg0)
}

// SendMessage mocks base method.
func (m *MockA2AStreamingClient) SendMessage(arg0 context.Context, arg1 interfaces.A2ASendMessageRequest) (interfaces.A2ASendMessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0, arg1)
	ret0, _ := ret[0].(interfaces.A2ASendMessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockA2AStreamingClientMockRecorder) SendMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockA2AStreamingClient)(nil).SendMessage), arg0, arg1)
}

// SendStreamingMessage mocks base method.
func (m *MockA2AStreamingClient) SendStreamingMessage(arg0 context.Context, arg1 interfaces.A2ASendMessageRequest) (interfaces.A2AStreamSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendStreamingMessage", arg0, arg1)
	ret0, _ := ret[0].(interfaces.A2AStreamSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendStreamingMessage indicates an expected call of SendStreamingMessage.
func (mr *MockA2AStreamingClientMockRecorder) SendStreamingMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendStreamingMessage", reflect.TypeOf((*MockA2AStreamingClient)(nil).SendStreamingMessage), arg0, arg1)
}

// MockA2ATaskClient is a mock of A2ATaskClient interface.
type MockA2ATaskClient struct {
	ctrl     *gomock.Controller
	recorder *MockA2ATaskClientMockRecorder
}

// MockA2ATaskClientMockRecorder is the mock recorder for MockA2ATaskClient.
type MockA2ATaskClientMockRecorder struct {
	mock *MockA2ATaskClient
}

// NewMockA2ATaskClient creates a new mock instance.
func NewMockA2ATaskClient(ctrl *gomock.Controller) *MockA2ATaskClient {
	mock := &MockA2ATaskClient{ctrl: ctrl}
	mock.recorder = &MockA2ATaskClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockA2ATaskClient) EXPECT() *MockA2ATaskClientMockRecorder {
	return m.recorder
}

// CancelTask mocks base method.
func (m *MockA2ATaskClient) CancelTask(arg0 context.Context, arg1 string) (interfaces.A2ATask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTask", arg0, arg1)
	ret0, _ := ret[0].(interfaces.A2ATask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelTask indicates an expected call of CancelTask.
func (mr *MockA2ATaskClientMockRecorder) CancelTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTask", reflect.TypeOf((*MockA2ATaskClient)(nil).CancelTask), arg0, arg1)
}

// Close mocks base method.
func (m *MockA2ATaskClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockA2ATaskClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockA2ATaskClient)(nil).Close))
}

// GetTask mocks base method.
func (m *MockA2ATaskClient) GetTask(arg0 context.Context, arg1 string) (interfaces.A2ATask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1)
	ret0, _ := ret[0].(interfaces.A2ATask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockA2ATaskClientMockRecorder) GetTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockA2ATaskClient)(nil).GetTask), arg0, arg1)
}

// ListSkills mocks base method.
func (m *MockA2ATaskClient) ListSkills(arg0 context.Context) ([]types.A2ASkillSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", arg0)
	ret0, _ := ret[0].([]types.A2ASkillSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockA2ATaskClientMockRecorder) ListSkills(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockA2ATaskClient)(nil).ListSkills), arg0)
}

// Name mocks base method.
func (m *MockA2ATaskClient) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockA2ATaskClientMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockA2ATaskClient)(nil).Name))
}

// Ping mocks base method.
func (m *MockA2ATaskClient) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockA2ATaskClientMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockA2ATaskClient)(nil).Ping), arg0)
}

// ResolveCard mocks base method.
func (m *MockA2ATaskClient) ResolveCard(arg0 context.Context) (interfaces.A2AAgentCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCard", arg0)
	ret0, _ := ret[0].(interfaces.A2AAgentCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCard indicates an expected call of ResolveCard.
func (mr *MockA2ATaskClientMockRecorder) ResolveCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCard", reflect.TypeOf((*MockA2ATaskClient)(nil).ResolveCard), arg0)
}

// SendMessage mocks base method.
func (m *MockA2ATaskClient) SendMessage(arg0 context.Context, arg1 interfaces.A2ASendMessageRequest) (interfaces.A2ASendMessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0, arg1)
	ret0, _ := ret[0].(interfaces.A2ASendMessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockA2ATaskClientMockRecorder) SendMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockA2ATaskClient)(nil).SendMessage), arg0, arg1)
}
